#!/usr/bin/env python3
"""Generate self-contained extension installers for non-technical teammates.

Reads every file under extension/ and bakes them (base64) into two one-file
installers — install-hr-attendance.sh (macOS/Linux) and
install-hr-attendance.ps1 (Windows). Running an installer writes the extension
folder to a stable local path, copies that path to the clipboard, and prints
the "Load unpacked" steps. No git, repo access, or separate download needed.

Re-run this whenever the extension/ files change:
    python3 scripts/build-installers.py
"""
import base64
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXT = os.path.join(ROOT, "extension")
DEST_NAME = "HRToolAttendance"  # folder the installer creates (no spaces)


def collect():
    files = []
    for dirpath, _dirs, names in os.walk(EXT):
        for name in sorted(names):
            full = os.path.join(dirpath, name)
            rel = os.path.relpath(full, EXT).replace(os.sep, "/")
            with open(full, "rb") as f:
                files.append((rel, base64.b64encode(f.read()).decode("ascii")))
    files.sort()
    return files


def wrap(b64, width=76):
    return "\n".join(b64[i : i + width] for i in range(0, len(b64), width))


def build_sh(files):
    out = []
    out.append("#!/usr/bin/env bash")
    out.append("# HR Tool Attendance — self-contained extension installer (macOS/Linux).")
    out.append("# Generated by scripts/build-installers.py — do not edit by hand.")
    out.append("set -euo pipefail")
    out.append("")
    out.append(f'DEST="$HOME/{DEST_NAME}"')
    out.append("")
    out.append('echo "HR Tool Attendance — installer"')
    out.append('echo')
    out.append('rm -rf "$DEST"')
    out.append("")
    out.append("write_file() {")
    out.append('  mkdir -p "$DEST/$(dirname "$1")"')
    out.append('  base64 -d > "$DEST/$1"')
    out.append("}")
    out.append("")
    for rel, b64 in files:
        out.append(f"write_file {sh_quote(rel)} <<'B64'")
        out.append(wrap(b64))
        out.append("B64")
    out.append("")
    out.append('echo "Extension installed at:"')
    out.append('echo "  $DEST"')
    out.append("")
    out.append("# Copy the path to the clipboard (best effort).")
    out.append('if command -v pbcopy >/dev/null 2>&1; then printf "%s" "$DEST" | pbcopy; COPIED=1;')
    out.append('elif command -v wl-copy >/dev/null 2>&1; then printf "%s" "$DEST" | wl-copy; COPIED=1;')
    out.append('elif command -v xclip >/dev/null 2>&1; then printf "%s" "$DEST" | xclip -selection clipboard; COPIED=1;')
    out.append("else COPIED=0; fi")
    out.append('[ "$COPIED" = 1 ] && echo "  (path copied to your clipboard)"')
    out.append("")
    out.append('cat <<STEPS')
    out.append("")
    out.append("Next, in your browser (works the same in all of these):")
    out.append("  1. Open your browser's extensions page:")
    out.append("       Chrome   ->  chrome://extensions")
    out.append("       Edge     ->  edge://extensions")
    out.append("       Brave    ->  brave://extensions")
    out.append("       Opera    ->  opera://extensions")
    out.append("       Vivaldi  ->  vivaldi://extensions")
    out.append("  2. Turn ON 'Developer mode' (top-right toggle; Edge: bottom-left)")
    out.append("  3. Click 'Load unpacked'")
    out.append("  4. Paste the path above into the folder box and choose it")
    out.append("  5. Pin 'HR Tool Attendance', click it, sign in with your work email + the")
    out.append("     6-digit code we email you")
    out.append("")
    out.append("Shortcuts once connected:")
    out.append("  Alt+Shift+I  = clock in")
    out.append("  Alt+Shift+O  = clock out")
    out.append("STEPS")
    out.append("")
    return "\n".join(out) + "\n"


def build_ps1(files):
    out = []
    out.append("# HR Tool Attendance - self-contained extension installer (Windows).")
    out.append("# Generated by scripts/build-installers.py - do not edit by hand.")
    out.append("# Run:  powershell -ExecutionPolicy Bypass -File install-hr-attendance.ps1")
    out.append("$ErrorActionPreference = 'Stop'")
    out.append("")
    out.append(f"$Dest = Join-Path $env:LOCALAPPDATA '{DEST_NAME}'")
    out.append("")
    out.append("Write-Host 'HR Tool Attendance - installer' -ForegroundColor Cyan")
    out.append("Write-Host ''")
    out.append("if (Test-Path $Dest) { Remove-Item -Recurse -Force $Dest }")
    out.append("")
    out.append("function Write-Ext($rel, $b64) {")
    out.append("  $p = Join-Path $Dest $rel")
    out.append("  $dir = Split-Path $p -Parent")
    out.append("  New-Item -ItemType Directory -Force -Path $dir | Out-Null")
    out.append("  [IO.File]::WriteAllBytes($p, [Convert]::FromBase64String($b64))")
    out.append("}")
    out.append("")
    for rel, b64 in files:
        out.append(f"Write-Ext '{rel}' '{b64}'")
    out.append("")
    out.append("Write-Host 'Extension installed at:'")
    out.append("Write-Host \"  $Dest\" -ForegroundColor Green")
    out.append("Set-Clipboard -Value $Dest")
    out.append("Write-Host '  (path copied to your clipboard)'")
    out.append("Write-Host ''")
    out.append("Write-Host 'Next, in your browser (works the same in all of these):'")
    out.append("Write-Host '  1. Open your browsers extensions page:'")
    out.append("Write-Host '       Chrome   ->  chrome://extensions'")
    out.append("Write-Host '       Edge     ->  edge://extensions'")
    out.append("Write-Host '       Brave    ->  brave://extensions'")
    out.append("Write-Host '       Opera    ->  opera://extensions'")
    out.append("Write-Host '       Vivaldi  ->  vivaldi://extensions'")
    out.append("Write-Host \"  2. Turn ON 'Developer mode' (top-right toggle; Edge: bottom-left)\"")
    out.append("Write-Host \"  3. Click 'Load unpacked'\"")
    out.append("Write-Host '  4. Paste the path above into the folder box and choose it'")
    out.append("Write-Host \"  5. Pin 'HR Tool Attendance', click it, sign in with your work email\"")
    out.append("Write-Host '     + the 6-digit code we email you'")
    out.append("Write-Host ''")
    out.append("Write-Host 'Shortcuts once connected:'")
    out.append("Write-Host '  Alt+Shift+I  = clock in'")
    out.append("Write-Host '  Alt+Shift+O  = clock out'")
    out.append("")
    return "\n".join(out) + "\n"


def sh_quote(s):
    return "'" + s.replace("'", "'\\''") + "'"


def main():
    files = collect()
    sh_path = os.path.join(ROOT, "install-hr-attendance.sh")
    ps1_path = os.path.join(ROOT, "install-hr-attendance.ps1")
    with open(sh_path, "w", newline="\n") as f:
        f.write(build_sh(files))
    os.chmod(sh_path, 0o755)
    with open(ps1_path, "w", newline="\r\n") as f:
        f.write(build_ps1(files))
    print(f"Wrote {sh_path}")
    print(f"Wrote {ps1_path}")
    print(f"Embedded {len(files)} files: {', '.join(r for r, _ in files)}")


if __name__ == "__main__":
    main()
